#!/usr/bin/bash
#
# pvscan
# A script to discover Preprocessor Variables used in source files
#
# If no arguments are provided, the entire source tree is scanned
#
# @param '$@' The list of source files to scan

set -o errexit
set -o nounset
set -o pipefail
shopt -s lastpipe

##
# Search for preprocessor variables in a file
#
# @param '$1' The file to scan
function pvscan
{
	# shellcheck disable=2016
	readonly vpattern='\$__.*__'
	grep -Eoe "$vpattern" "$1"
}

##
# Search for preprocessor variables in a list of files
# parallelizing the operation
#
# If no arguments are provided
# the list of files to scan is acquired through stdin
#
# @param '$@' The list of files to scan
function pvscanFiles
{
	if [ $# -eq 0 ] ; then

		local srcFile
		while read -r srcFile ; do
			pvscan "$srcFile" &
		done

	else

		for f in "$@" ; do
			pvscan "$f" &
		done

	fi
}

# Script entry point

if [ $# -eq 0 ] ; then
	find src -type f | pvscanFiles | sort -u
else
	pvscanFiles "$@" | sort -u
fi